version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    networks:
      - springapipostgresql-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - springapipostgresql-net
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appdb
volumes:
  postgres-data:
networks:
  springapipostgresql-net: